<a href="https://colab.research.google.com/github/MrH101/Data_analytics/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A Numpy practical Tutorial 

##**Use numpy array instead of python lists because it is fast,convenient and takes less memory**

In [1]:
import numpy as np

**Creating Arrays**

In [2]:
#random arrays
data =np.random.rand(2,3,4)
data

array([[[0.86416795, 0.97161084, 0.66293531, 0.79538061],
        [0.10991524, 0.24081543, 0.41275346, 0.12807496],
        [0.13264538, 0.75809357, 0.44765535, 0.58021406]],

       [[0.08061826, 0.54649518, 0.97419193, 0.36597698],
        [0.76182174, 0.96924936, 0.97730771, 0.48500758],
        [0.45262231, 0.05525025, 0.61396053, 0.42388277]]])

In [3]:
#array of ones
dt =np.ones((2,2,2))
dt

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [4]:
#array of zeros
dt_0 =np.zeros((2,2,2))
dt_0

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [5]:
#full arrays
full = np.full((2,2,2),7)
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

##to create an array use np.array() function

In [6]:
arr = np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


**printing dimensional arrays**
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [7]:
#0 dimensional
arr_0 = np.array(56)
print(arr_0)

56


In [8]:
# 1 dimensional 
arr_1 = np.array([1,2,3,4,5,6,7])
print(arr_1)

[1 2 3 4 5 6 7]


In [9]:
#2 dimensional:an array that has 1 d arrays as its elements
#These are often used to represent matrix or 2nd order tensors.
arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#3 dimensional arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.
arr_3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4,],[5,6,7,8]]])
print(arr_3)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [11]:
#checking the dimensions of an array
print(arr_0.ndim)
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)

0
1
2
3


In [12]:
#creating arrays of higher dimensions 
